import { HomeScreenWidget } from "@/components/home-screen/HomeScreenWidget";
import { GithubIcon } from "@/svg-icons/github-icon";
import { Navbar, NavbarBrand, NavbarContent } from "@nextui-org/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notifi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center">
        <div className="flex-1">
          <HomeScreenWidget />
        </div>
        <div className="flex w-full justify-between text-sm text-gray-700">
          <Navbar maxWidth="2xl">
            <NavbarBrand className="text-sm">
              <div>&copy; {new Date().getFullYear()} @emilshr.com</div>
            </NavbarBrand>
            <div>
              <NavbarContent>
                <Link
                  href="https://github.com/emilshr/notifi-stack"
                  target="_blank"
                >
                  <GithubIcon />
                </Link>
              </NavbarContent>
            </div>
          </Navbar>
        </div>
      </main>
    </>
  );
}
