import { HomeScreenWidget } from "@/components/project-dashboard/HomeScreenWidget";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-center">
        <HomeScreenWidget />
      </main>
    </>
  );
}
